# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd109382622cad849d0978ee755436f73af0b2eb5d3bfca4f68895f068ff4afe1a3ac55583738d3846bc6a7944612e95a21ba8baa904cbc35371fae537072337

test:
  secret_key_base: 9d7c7e88ac3e233d7699c8f2538714ca705b0af61a174d7d2cdd7dd1b06875538004d0bd792d69dd80a91ca4cdc056c61b15111f59b1bfe3ce5c83e80fd189af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
